project:
  type: website
  output-dir: docs

website:
  title: "intRos"
  site-url: https://exeter-data-analytics.github.io/intRos/
  repo-url: https://github.com/exeter-data-analytics/intRos
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Walkthroughs
format:
  html:
    theme: minty
    css: styles.css
    toc: true



