project:
  type: website
  output-dir: docs

website:
  title: "intRos"
  google-analytics: G-7BMXZGJQQY
  site-url: https://exeter-data-analytics.github.io/intRos/
  repo-url: https://github.com/exeter-data-analytics/intRos
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Walkthroughs
      - icon: github
        href: https://github.com/exeter-data-analytics/intRos
format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true
    
comments:
  giscus:
    repo: exeter-data-analytics/intRos
      



