---
title: "intRos: Reproducible tables with flextable"
author: 
  - name: Daniel Padfield
    affiliation: University of Exeter
description: "Make reproducible tables of summary stats and contrasts tables with flextable in R"
date: "10/02/2023"
categories: [flextable, R]
image: ""
---

# Outline

As scientists we make A LOT of tables, be it of summary statistics, model parameter values, contrast tables, or anything else. It used to be common practice to copy these individually into Excel or Word and then create a table to insert into your work, but this is prone to errors. No one is perfect after all.

This problem has now been solved by a bunch of different packages that allow for tables to be created in R and exported to a variety of formats. This means that fewer mistakes are made, that tables can easily be remade if the data or stats change, and that the process of making your tables is completely reproducible. The R package we will introduce to do this today is **flextable**, but there are other options available we won't cover here such as **gt**. 

**flextable** provides an easy and flexible way to create tables for reporting and presentations. It allows for customization of the table appearance, including cell borders, font styles, background color, and more. The package also supports different formats such as HTML, Microsoft Word, and PowerPoint. It is well suited for creating reports and presentations with a high level of formatting, while still being simple and straightforward to use. Additionally, **flextable** has a number of features that make it particularly useful for data visualisation, including the ability to merge cells, add custom functions for data formatting, and control the appearance of the table based on data values (i.e. making p values that are <0.05 **bold**).

# Prerequisites

# Learning objectives

::: callout-note
# Learning objectives

**This introduction should allow you to:**

-   Add here.
:::

# Using flextable

### Load in required packages

## Make table of summary stats

## Make table of model parameters

## Make table of contrasts

# Summary

### Additional Resources

### Acknowledgements

We did not create this content alone! Inspiration, tips, and resources have been borrowed from multiple sources.

-   Add here.

